CREATE SCHEMA IF NOT EXISTS "locations";

CREATE TABLE "locations"."tb_location" (
  "pk_location"   uuid PRIMARY KEY,
  "idx_location"  bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  "tx_street"     varchar(128),
  "tx_number"     varchar(128),
  "tx_city"       varchar(128),
  "tx_state"      varchar(2),
  "tx_zipCode"    varchar(9),
);
