CREATE SCHEMA IF NOT EXISTS "users";

CREATE TABLE "users"."tb_user" (
  "pk_user" uuid PRIMARY KEY,
  "idx_user" BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  "tx_name" varchar(100) NOT NULL,
  "tx_password_hash" varchar(255) NOT NULL,
  "tx_role" varchar(124),
  "fk_contact" uuid,
  "ts_created_at" timestamp DEFAULT (now()),
  "ts_updated_at" timestamp
);

CREATE TABLE "users"."tb_contact" (
  "pk_contact" uuid PRIMARY KEY
);

ALTER TABLE "users"."tb_user" ADD FOREIGN KEY ("fk_contact") REFERENCES "users"."tb_contact" ("pk_contact");

ALTER TABLE "users"."tb_contact" ADD FOREIGN KEY ("pk_contact") REFERENCES "contacts"."tb_contact" ("pk_contact");