[package]
name = "milions-sys"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true }
sqlx = { workspace = true }
rsa = { workspace = true }
rand = { workspace = true }
secrecy = { workspace = true }
services = { path = "services" }
config = { path = "config" }
rest = { path = "rest" }

[workspace]
members = ["config", "domain", "repository", "rest", "services"]

[workspace.dependencies]
repository = { path = "repository" }
actix-web = { version = "4.3.3" }
regex = "1.12.3"
testcontainers = "0.27.1"
argon2 = "0.5.3"
snafu = { version = "0.9.0", features = ["futures", "default", "std"] }
thiserror = "2.0.18"
chrono = { version = "0.4.26", features = ["serde"] }
uuid = { version = "1.21.0", features = ["v4", "serde", "v7"] }
secrecy = { version = "0.10.0", features = ["serde"] }
serde-aux = "4.7.0"
serde = { version = "1.0.183", features = ["derive"] }
keycloak = { version = "26.5.200" }
sqlx = { version = "0.8.6", features = [
  "runtime-tokio",
  "tls-native-tls",
  "postgres",
  "macros",
  "uuid",
  "chrono",
  "migrate",
  "bigdecimal",
] }
tokio = { version = "1.48.0", features = ["full"] }
anyhow = { version = "1.0.75", default-features = false }
rsa = { version = "0.9.10" }
rand = "0.10.0"

[lints.rust]
dead_code = "allow"
