CREATE SCHEMA IF NOT EXISTS "locations";

CREATE TABLE "locations"."tb_location" (
  "pk_location" uuid PRIMARY KEY,
  "idx_location" BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  "street" varchar2(256),
  "number" varchar2(32),
  "city" varchar2(128),
  "state" varchar2(2),
  "zipCode" varchar2(9)
);
