CREATE SCHEMA if not exists "contacts";

CREATE TABLE "contacts"."tb_contact" (
  "pk_contact" uuid PRIMARY KEY,
  "idx_contact" BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  "tx_phone" varchar(16),
  "tx_email" varchar(256) UNIQUE,
  "ts_contact_created_at" timestamp NOT NULL,
  "ts_contact_updated_at" timestamp NOT NULL
);

CREATE TABLE "contacts"."tb_phone" (
  "pk_phone" uuid PRIMARY KEY,
  "idx_phone" BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  "tx_phone" varchar(16),
  "fk_contact" uuid NOT NULL,
  "ts_phone_created_at" timestamp NOT NULL,
  "ts_phone_updated_at" timestamp NOT NULL
);

CREATE TABLE "contacts"."tb_address" (
  "pk_address" uuid PRIMARY KEY,
  "idx_address" BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  "fk_contact" uuid,
  "ts_address_created_at" timestamp NOT NULL,
  "ts_address_updated_at" timestamp NOT NULL
);

ALTER TABLE "contacts"."tb_phone" ADD FOREIGN KEY ("fk_contact") REFERENCES "contacts"."tb_contact" ("pk_contact");

ALTER TABLE "contacts"."tb_address" ADD FOREIGN KEY ("fk_contact") REFERENCES "contacts"."tb_contact" ("pk_contact");

ALTER TABLE "contacts"."tb_address" ADD FOREIGN KEY ("pk_address") REFERENCES "locations"."tb_location" ("pk_location");