CREATE SCHEMA IF NOT EXISTS locations;
CREATE TABLE IF NOT EXISTS locations.tb_location(
  pk_location UUID PRIMARY KEY,
  idx_location BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  tx_street VARCHAR(128) NOT NULL,
  tx_number VARCHAR(128) NOT NULL,
  tx_city VARCHAR(128) NOT NULL,
  tx_state VARCHAR(2) NOT NULL,
  tx_zipcode VARCHAR(9) NOT NULL,
  ts_location_created_at TIMESTAMP DEFAULT NOW() NOT NULL,
  ts_location_updated_at TIMESTAMP DEFAULT NOW() NOT NULL
);
