CREATE SCHEMA if NOT EXISTS "contacts";
CREATE TABLE "contacts"."tb_contact"(
  "pk_contact" UUID PRIMARY KEY,
  "idx_contact" BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  "tx_phone"VARCHAR(16),
  "tx_email"VARCHAR(256) UNIQUE,
  "ts_contact_created_at" TIMESTAMP DEFAULT NOW() NOT NULL,
  "ts_contact_updated_at" TIMESTAMP DEFAULT NOW() NOT NULL
);

CREATE TABLE "contacts"."tb_phone"(
  "pk_phone" UUID PRIMARY KEY,
  "idx_phone" BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  "tx_phone"VARCHAR(16),
  "fk_contact" UUID NOT NULL,
  "ts_phone_created_at" TIMESTAMP DEFAULT NOW() NOT NULL,
  "ts_phone_updated_at" TIMESTAMP DEFAULT NOW() NOT NULL
);
ALTER TABLE "contacts"."tb_phone" ADD FOREIGN KEY("fk_contact") REFERENCES "contacts"."tb_contact"("pk_contact");

CREATE TABLE "contacts"."tb_address"(
  "pk_address" UUID PRIMARY KEY,
  "idx_address" BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  "fk_contact" UUID NOT NULL,
  "fk_address" UUID,
  "ts_address_created_at" TIMESTAMP DEFAULT NOW() NOT NULL,
  "ts_address_updated_at" TIMESTAMP DEFAULT NOW() NOT NULL
);
ALTER TABLE "contacts"."tb_address" ADD FOREIGN KEY("fk_contact") REFERENCES "contacts"."tb_contact"("pk_contact");
ALTER TABLE "contacts"."tb_address" ADD FOREIGN KEY("pk_address") REFERENCES "locations"."tb_location"("pk_location");
