CREATE SCHEMA IF NOT EXISTS locations;
CREATE TABLE IF NOT EXISTS locations.tb_location(
  pk_location UUID PRIMARY KEY,
  idx_location BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  tx_public_space VARCHAR(128) NOT NULL,
  tx_address_complement VARCHAR(256),
  tx_unit VARCHAR(64) NOT NULL,
  tx_neighborhood VARCHAR(128) NOT NULL,
  tx_locality VARCHAR(128) NOT NULL,
  tx_region VARCHAR(64) NOT NULL,
  tx_ibge VARCHAR(16) NOT NULL,
  tx_gia VARCHAR(16)  ,
  tx_ddd VARCHAR(3) NOT NULL,
  tx_siafi VARCHAR(8) NOT NULL,
  tx_street VARCHAR(128) NOT NULL,
  tx_number VARCHAR(128) NOT NULL,
  tx_city VARCHAR(128) NOT NULL,
  tx_state VARCHAR(2) NOT NULL,
  tx_zipcode VARCHAR(9) NOT NULL,
  ts_location_created_at TIMESTAMP DEFAULT NOW() NOT NULL,
  ts_location_updated_at TIMESTAMP DEFAULT NOW() NOT NULL
);
