CREATE SCHEMA IF NOT EXISTS "clients";

CREATE TABLE "clients"."tb_client"(
  "pk_client" UUID PRIMARY KEY,
  "idx_client" BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  "tx_name" VARCHAR(64) NOT NULL,
  "tx_email"VARCHAR(256) UNIQUE NOT NULL,
  "ts_client_created_at" TIMESTAMP NOT NULL,
  "ts_client_updated_at" TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS "clients"."tb_client_contact"(
  "pk_client_contact" UUID PRIMARY KEY,
  "idx_client_contact" BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  "fk_client" UUID NOT NULL,
  "fk_contact" UUID NOT NULL,
  "ts_client_contact_created_at" TIMESTAMP NOT NULL,
  "ts_client_contact_updated_at" TIMESTAMP NOT NULL
);
ALTER TABLE "clients"."tb_client_contact" ADD FOREIGN KEY("fk_client") REFERENCES "clients"."tb_client"("pk_client");
ALTER TABLE "clients"."tb_client_contact" ADD FOREIGN KEY("fk_contact") REFERENCES "contacts"."tb_contact"("pk_contact");

CREATE TABLE IF NOT EXISTS "clients"."tb_client_address"(
  "pk_client_address" UUID PRIMARY KEY,
  "idx_client_address" BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  "fk_client" UUID NOT NULL,
  "fk_address" UUID NOT NULL,
  "ts_client_address_created_at" TIMESTAMP NOT NULL,
  "ts_client_address_updated_at" TIMESTAMP NOT NULL
);
ALTER TABLE "clients"."tb_client_address" ADD FOREIGN KEY("fk_client") REFERENCES "clients"."tb_client"("pk_client");
ALTER TABLE "clients"."tb_client_address" ADD FOREIGN KEY("fk_address") REFERENCES "locations"."tb_location"("pk_location");

CREATE TABLE "clients"."tb_project"(
  "pk_project" UUID PRIMARY KEY,
  "idx_project" BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  "tx_name" VARCHAR(64) NOT NULL,
  "tx_status" VARCHAR NOT NULL,
  "fk_address" UUID NOT NULL,
  "fk_client" UUID NOT NULL,
  "ts_project_created_at" TIMESTAMP NOT NULL,
  "ts_project_updated_at" TIMESTAMP NOT NULL
);
ALTER TABLE "clients"."tb_project" ADD FOREIGN KEY("fk_address") REFERENCES "locations"."tb_location"("pk_location");
ALTER TABLE "clients"."tb_project" ADD FOREIGN KEY("fk_client") REFERENCES "clients"."tb_client"("pk_client");

CREATE TABLE "clients"."tb_allocated_collaborator"(
  "pk_allocated_collaborator" UUID PRIMARY KEY,
  "idx_allocated_collaborator" BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  "fk_collaborator" UUID NOT NULL,
  "fk_project" UUID NOT NULL
);
ALTER TABLE "clients"."tb_allocated_collaborator" ADD FOREIGN KEY("fk_project") REFERENCES "clients"."tb_project"("pk_project");
ALTER TABLE "clients"."tb_allocated_collaborator" ADD FOREIGN KEY("pk_allocated_collaborator") REFERENCES "collaborators"."tb_collaborator"("pk_collaborator");


