CREATE SCHEMA "collaborators";
CREATE TABLE "collaborators"."tb_collaborator"(
  "pk_collaborator" UUID PRIMARY KEY,
  "idx_collaborator" BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  "tx_name" VARCHAR(64) NOT NULL,
  "tx_level"VARCHAR(16) NOT NULL,
  "ts_collaborator_created_at" TIMESTAMP NOT NULL,
  "ts_collaborator_updated_at" TIMESTAMP NOT NULL
);

CREATE TABLE "collaborators"."tb_collaborator_address"(
  "pk_collaborator_address" UUID PRIMARY KEY,
  "idx_collaborator_address" BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  "fk_collaborator" UUID NOT NULL,
  "fk_address" UUID NOT NULL,
  "ts_collaborator_address_created_at" TIMESTAMP NOT NULL,
  "ts_collaborator_address_updated_at" TIMESTAMP NOT NULL
);
ALTER TABLE "collaborators"."tb_collaborator_address" ADD FOREIGN KEY("fk_address") REFERENCES "locations"."tb_location"("pk_location");
ALTER TABLE "collaborators"."tb_collaborator_address" ADD FOREIGN KEY("fk_collaborator") REFERENCES "collaborators"."tb_collaborator"("pk_collaborator");

CREATE TABLE "collaborators"."tb_collaborator_contact"(
  "pk_collaborator_contact" UUID PRIMARY KEY,
  "idx_collaborator_contact" BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  "fk_collaborator" UUID NOT NULL,
  "fk_contact" UUID NOT NULL,
  "ts_collaborator_contact_created_at" TIMESTAMP NOT NULL,
  "ts_collaborator_contact_updated_at" TIMESTAMP NOT NULL
);
ALTER TABLE "collaborators"."tb_collaborator_contact" ADD FOREIGN KEY("fk_collaborator") REFERENCES "collaborators"."tb_collaborator"("pk_collaborator");
ALTER TABLE "collaborators"."tb_collaborator_contact" ADD FOREIGN KEY("fk_contact") REFERENCES "contacts"."tb_contact"("pk_contact");
