CREATE SCHEMA IF NOT EXISTS "contacts";
CREATE TABLE "contacts"."tb_contact"(
  "pk_contact" UUID PRIMARY KEY,
  "idx_contact" BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  "tx_email" VARCHAR(256) UNIQUE,
  "ts_contact_created_at" TIMESTAMP DEFAULT NOW() NOT NULL,
  "ts_contact_updated_at" TIMESTAMP DEFAULT NOW() NOT NULL
);

CREATE TABLE "contacts"."tb_phone"(
  "pk_phone" UUID PRIMARY KEY,
  "idx_phone" BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  "tx_phone" VARCHAR(16) UNIQUE NOT NULL,
  "fk_contact" UUID NOT NULL,
  "ts_phone_created_at" TIMESTAMP DEFAULT NOW() NOT NULL,
  "ts_phone_updated_at" TIMESTAMP DEFAULT NOW() NOT NULL
);
ALTER TABLE "contacts"."tb_phone"
  ADD FOREIGN KEY("fk_contact") REFERENCES "contacts"."tb_contact"("pk_contact")
  ON DELETE CASCADE;

CREATE INDEX idx_tb_phone_fk_contact ON "contacts"."tb_phone" ("fk_contact");
