CREATE SCHEMA IF NOT EXISTS "clients";

CREATE TABLE "clients"."tb_client"(
  "pk_client" UUID PRIMARY KEY,
  "idx_client" BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  "tx_name" VARCHAR(64) NOT NULL,
  "tx_email"VARCHAR(256) UNIQUE NOT NULL,
  "ts_client_created_at" TIMESTAMP NOT NULL,
  "ts_client_updated_at" TIMESTAMP NOT NULL
);

CREATE TABLE "clients"."tb_job"(
  "pk_clients" UUID PRIMARY KEY,
  "idx_clients" BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  "tx_name" VARCHAR(64) NOT NULL,
  "tx_status" VARCHAR NOT NULL,
  "fk_address" UUID NOT NULL,
  "fk_client" UUID NOT NULL,
  "ts_job_created_at" TIMESTAMP NOT NULL,
  "ts_job_updated_at" TIMESTAMP NOT NULL
);
ALTER TABLE "clients"."tb_job" ADD FOREIGN KEY("fk_address") REFERENCES "locations"."tb_location"("pk_location");
ALTER TABLE "clients"."tb_job" ADD FOREIGN KEY("fk_client") REFERENCES "clients"."tb_client"("pk_client");

CREATE TABLE "clients"."tb_allocated_collaborator"(
  "pk_allocated_collaborator" UUID PRIMARY KEY,
  "idx_allocated_collaborator" BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  "fk_collaborator" UUID NOT NULL,
  "fk_job" UUID NOT NULL
);
ALTER TABLE "clients"."tb_allocated_collaborator" ADD FOREIGN KEY("fk_job") REFERENCES "clients"."tb_job"("pk_clients");
ALTER TABLE "clients"."tb_allocated_collaborator" ADD FOREIGN KEY("pk_allocated_collaborator") REFERENCES "collaborators"."tb_collaborator"("pk_collaborator");


