[package]
name = "contact"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
types = { path = "../types" }
sqlx = { workspace = true }
uuid = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
actix-web = { workspace = true }
thiserror = { workspace = true }
snafu = { workspace = true }
regex = { workspace = true}
async-trait = "0.1.89"
chrono = { workspace = true }

[lints.rust]

[dev-dependencies]
tokio = { workspace = true }
