[package]
name = "location"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
domain = { path = "../domain" }
sqlx = { workspace = true }
uuid = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
snafu = { workspace = true }
async-trait = "0.1.89"
chrono = { workspace = true }

[lints.rust]
dead_code = "allow"
